CFLAGS=-Wall -g

LDFLAGS=-lm

Project3_zluo2_207 : Project3_main_zluo2_207.c Project3_llist_zluo2_207.c
	gcc -o Project3_zluo2_207 Project3_main_zluo2_207.c Project3_llist_zluo2_207.c $(CFLAGS) $(LDFLAGS)

clean:	
	rm -f Project3_zluo2_207

